/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_secube_SECubeConnector */

#ifndef _Included_org_cryptomator_secube_SECubeConnector
#define _Included_org_cryptomator_secube_SECubeConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_secube_SECubeConnector
 * Method:    EnumerateDevices
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_cryptomator_secube_SECubeConnector_EnumerateDevices
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_secube_SECubeConnector
 * Method:    GenerateSecurePasswordOnDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_secube_SECubeConnector_GenerateSecurePasswordOnDevice
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_cryptomator_secube_SECubeConnector
 * Method:    GetSecurePasswordOnDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_secube_SECubeConnector_GetSecurePasswordOnDevice
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
